import { Plus, Trash2, GripVertical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

interface AnalyticsInput {
  id: string;
  label: string;
  sourceTag?: string;
}

interface AnalyticsInputsEditorProps {
  value: AnalyticsInput[];
  onChange: (value: AnalyticsInput[]) => void;
}

// Convert label to snake_case for source tag
function toSnakeCase(str: string): string {
  return str
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '') // Remove special characters
    .replace(/\s+/g, '_'); // Replace spaces with underscores
}

export function AnalyticsInputsEditor({ value, onChange }: AnalyticsInputsEditorProps) {
  const inputs = Array.isArray(value) ? value : [];

  const addInput = () => {
    const inputNumber = inputs.length + 1;
    const label = `Input ${inputNumber}`;
    const newInput: AnalyticsInput = {
      id: `input${inputNumber}`,
      label,
      sourceTag: toSnakeCase(label),
    };
    onChange([...inputs, newInput]);
  };

  const removeInput = (index: number) => {
    const newInputs = inputs.filter((_, i) => i !== index);
    onChange(newInputs);
  };

  const updateInput = (index: number, field: keyof AnalyticsInput, fieldValue: string) => {
    const newInputs = [...inputs];
    const currentInput = newInputs[index];

    // If updating the label, auto-populate source tag if it's empty or matches the auto-generated value
    if (field === 'label') {
      const currentSourceTag = currentInput.sourceTag || '';
      const autoGeneratedFromCurrentLabel = toSnakeCase(currentInput.label);

      // Update source tag if it's empty or matches what would be auto-generated from current label
      const shouldAutoUpdateSourceTag =
        currentSourceTag === '' || currentSourceTag === autoGeneratedFromCurrentLabel;

      newInputs[index] = {
        ...currentInput,
        label: fieldValue,
        ...(shouldAutoUpdateSourceTag && { sourceTag: toSnakeCase(fieldValue) }),
      };
    } else {
      newInputs[index] = { ...currentInput, [field]: fieldValue };
    }

    onChange(newInputs);
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <Label className="text-sm font-medium">Data Inputs</Label>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={addInput}
          className="h-7 text-xs gap-1"
        >
          <Plus className="h-3 w-3" />
          Add Input
        </Button>
      </div>

      {inputs.length === 0 ? (
        <div className="p-6 border-2 border-dashed rounded-lg text-center">
          <p className="text-sm text-muted-foreground mb-3">No data inputs configured</p>
          <p className="text-xs text-muted-foreground mb-4">
            Configure input ports to receive analytics results from different scanner components.
            Each input creates a corresponding input port on this node.
          </p>
          <Button type="button" variant="outline" size="sm" onClick={addInput} className="gap-1">
            <Plus className="h-3 w-3" />
            Add First Input
          </Button>
        </div>
      ) : (
        <div className="space-y-3">
          {inputs.map((input, index) => (
            <div key={index} className="p-3 border rounded-lg bg-background space-y-3">
              {/* Header with drag handle and delete */}
              <div className="flex items-center gap-2">
                <GripVertical className="h-4 w-4 text-muted-foreground cursor-move" />
                <span className="text-sm font-medium flex-1">Input {index + 1}</span>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6"
                  onClick={() => removeInput(index)}
                >
                  <Trash2 className="h-3 w-3 text-red-500" />
                </Button>
              </div>

              {/* ID Field */}
              <div className="space-y-1">
                <Label htmlFor={`input-${index}-id`} className="text-xs">
                  ID <span className="text-red-500">*</span>
                </Label>
                <Input
                  id={`input-${index}-id`}
                  value={input.id}
                  onChange={(e) => updateInput(index, 'id', e.target.value)}
                  placeholder="e.g., nucleiResults"
                  className="h-8 text-xs font-mono"
                />
                <p className="text-[10px] text-muted-foreground">
                  Unique identifier (becomes input port ID)
                </p>
              </div>

              {/* Label Field */}
              <div className="space-y-1">
                <Label htmlFor={`input-${index}-label`} className="text-xs">
                  Label <span className="text-red-500">*</span>
                </Label>
                <Input
                  id={`input-${index}-label`}
                  value={input.label}
                  onChange={(e) => updateInput(index, 'label', e.target.value)}
                  placeholder="e.g., Nuclei Results"
                  className="h-8 text-xs"
                />
                <p className="text-[10px] text-muted-foreground">Display name in workflow editor</p>
              </div>

              {/* Source Tag Field */}
              <div className="space-y-1">
                <Label htmlFor={`input-${index}-sourceTag`} className="text-xs">
                  Source Tag
                </Label>
                <Input
                  id={`input-${index}-sourceTag`}
                  value={input.sourceTag || ''}
                  onChange={(e) => updateInput(index, 'sourceTag', e.target.value)}
                  placeholder="e.g., nuclei-scan"
                  className="h-8 text-xs font-mono"
                />
                <p className="text-[10px] text-muted-foreground">
                  Added to indexed documents as &apos;source_input&apos; for filtering in dashboards
                  (optional)
                </p>
              </div>

              {/* Input Port Preview */}
              <div className="pt-2 border-t">
                <div className="flex items-center gap-2 text-xs">
                  <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                  <span className="text-muted-foreground">
                    Input port: <span className="font-mono text-blue-600">{input.id}</span>
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Summary */}
      {inputs.length > 0 && (
        <div className="p-3 bg-muted/50 rounded-lg border">
          <p className="text-xs text-muted-foreground">
            <span className="font-medium">{inputs.length}</span> data input
            {inputs.length !== 1 ? 's' : ''} configured
          </p>
          <p className="text-xs text-muted-foreground mt-1">
            {inputs.length} input port{inputs.length !== 1 ? 's' : ''} will be created on this node
          </p>
        </div>
      )}
    </div>
  );
}
