export const PROVISIONING_REDIS = Symbol('PROVISIONING_REDIS');
export const INSTANCE_HEARTBEAT_REDIS = Symbol('INSTANCE_HEARTBEAT_REDIS');
export const TICKETING_OAUTH_REDIS = Symbol('TICKETING_OAUTH_REDIS');
